server:
  port: 7003

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://124.193.68.152:25506/nanchang-lamp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://124.193.68.152:25506/nanchang-lamp-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/shiro?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    #password: root
    password: 123456
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
      allowMultiQuerie: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:static/

  # thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false
  #redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:       # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5

jsonFilePath: "file:D:/IdeaProjects/springcloudxuexi/nacos/"

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.pojo
  configuration:
    # 在控制台打印sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 使用驼峰命名法转换字段
    mapUnderscoreToCamelCase: true

