server:
  port: 7009


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://124.193.68.152:25506/nanchang-lamp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://124.193.68.152:25506/nanchang-lamp-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/shiro?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    #password: root
    password: 123456
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
      allowMultiQuerie: true

  #邮件配置
  mail:
    host: smtp.163.com
    username: t918126051@163.com
    password:
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: emailService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka/, http://eureka8002.com:8002/eureka/